### ISSUE TITLE
ropensci website changes

### ISSUE THREAD

**Issue by sckott** [ropensci/rdataretriever#104]
changed ecoretriever to rdataretriever on the pkgs page https://ropensci.org/packages/#rdataretriever 

tutorial updated https://ropensci.org/tutorials/rdataretriever_tutorial.html

old tutorial auto forwards to new one so isn't a broken  link https://ropensci.org/tutorials/ecoretriever_tutorial.html 

let me know if any changes

**Comment by ethanwhite** [comment]
Thanks @sckott! All of the changes you've made look good. There is one more, which is that the `Download page` link should now point to http://www.data-retriever.org/#install. The formatting of the output will have also changed a bit since the move to 2.0 so you may want to rerun when you get the chance.

**Comment by sckott** [comment]
Sure thing, will do.

**Comment by ethanwhite** [comment]
Awesome. Thanks.
