### ISSUE TITLE
Change naming object behavior of fetch

### ISSUE THREAD

**Issue by dmcglinn** [ropensci/rdataretriever#106]
Currently the function `fetch` concatenates the name of the dataset (e.g., mammal-community-db) to each element of the list which represent each datafile associated with a particular dataset. See https://github.com/ropensci/rdataretriever/blob/master/R/rdataretriever.R#L102

That line of code results in the following behavior: 
```
library(rdataretriever)
mcdb = fetch('mammal-community-db')
names(mcdb)
[1] "mammal_community_db_communities" "mammal_community_db_references" 
[3] "mammal_community_db_sites"       "mammal_community_db_species"    
[5] "mammal_community_db_trapping"   
```
which is unnecessarily cumbersome to work with. I propose that we remove that line of code. Any thoughts?

**Comment by henrykironde** [comment]
I am not sure how the data is stored when fetched, but adding the script makes those files unique.
if you have 2 datasets ie `mammal-community-db` and `portal`. and both have species table.
adding the script name as a prefix makes that file unique.

**Comment by henrykironde** [comment]
Incase thats not the case, we could go ahead and adjust for simplicity as you requested

**Comment by ethanwhite** [comment]
Following up on Henry's point, the core retriever works this way so that, e.g., the `species` tables from `mammal-community-db` and from `portal` can be stored in the same directory. In the case of the current use of `fetch` that is already handled since we're only fetching one dataset at a time so we'd be calling things like:

```
mcdb$species
```

in @dmcglinn's example. Given that I think it's fine to change the behavior. The one possible argument against it would be if we wanted to extend `fetch` to take a list of datasets, e.g.,:

```
data = fetch(c('mammal-community-db', 'mammal-masses', 'mammal-life-hist'))
```

but if we did that we could set it up so that the data is nested and we could call it like:

```
data$mammal_community_db$species
```

which seems generally more useful that combining all of the tables in an unnested list.

So, unless I'm missing a use case, I'm +1.
