### ISSUE TITLE
Switch to named list for returning fetched data

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/rdataretriever#136]
Currently fetch returns a list of data.frames, but the user has to know the order to work with them. Instead let's return a named list with the associated table names so that we can reference tables by name. E.g.,

```
data = rdataretriever::fetch('portal')
data['portal_surveys']
data$portal_surveys
```

**Comment by pranita-s** [comment]
@ethanwhite I have updated the code for named list in the commit https://github.com/ropensci/rdataretriever/pull/134/commits/fd530e966a761fd045db0995581fee2f63b22e7b.
Please let me know your thoughts about it.

**Comment by pranita-s** [comment]
@ethanwhite What are the exact requirements ?

**Comment by ethanwhite** [comment]
Hmmm, apparently a comment I tried to leave here yesterday didn't end up posting for some reason. Apologies for any associated confusion.

This is a particular instance of a case where we need to make cross-language decisions about what the API should look like so that it functions the same way in R, Python, and Julia (we have a wrapper under development there as well. I think there are two components to this:

1. A review of the R, Python, and Julia APIs that highlights any differences between them and anything that is missing in any of them.
2. As a piece of (1) a discussion of exactly what the fetch API should be that asks:
    * Should fetch support multiple datasets?
    * If supporting multiple datasets should it return a flat list with dataset names as part of the name or a nested list with dataset names as the top level name and table names nested within them?

For (2) I think the best way to pursue that is to open an issue for discussion in the main Python repository.

(1) is a bigger task, but is also central to the idea laid out for the `rdataretriever` GSoC project. Going through the APIs and documenting what is missing or different between them and starting to document this in issues in the R and Julia packages to work towards making the APIs consistent (while maintaining backward compatibility). This list of differences and ideas for fixing them would also be a useful part of the GSoC proposal.

**Comment by pranita-s** [comment]
@ethanwhite As I am working on a proposal, I am currently concentrating on R API and ideas list does not contain anything about Julia packages. Do I need to work with Julia package too?

**Comment by ethanwhite** [comment]
@pranita-s I don't think it's crucial to the proposal, but you might make the proposal stronger by highlighting that it will involve 3 of the major data science languages. I think it's fine to either include it or leave it out.

**Comment by ethanwhite** [comment]
I'm going to go ahead and close this since it's part of the larger API synchronization effort. When we've collectively decided on the route forward we can open a new issue with the details.

**Comment by pranita-s** [comment]
@ethanwhite @henrykironde I have a few doubts while working with Python API, R API and command line interface of retriever for proposal.
1. While running install for example with postgres, the given database is created with command line interface, but with Python and R API it displays - "database doesn't exist". Should this be an issue or I might be doing something wrong?
2. Retriever's command line interface contains "new_json,edit_json,delete_json". Will mentioning creation of these functions in R in proposal be apt?

**Comment by ethanwhite** [comment]
> 1. While running install for example with postgres, the given database is created with command line interface, but with Python and R API it displays - "database doesn't exist". Should this be an issue or I might be doing something wrong?

I get the same results when installing from the CLI and Python, which behaves normally. There are currently differences for the R package in that it relies on the existence of a `postgress.conn` file in the users home directory with connection information. If you have the tests running locally then this file should be:

```
host localhost
port 5432
user postgres
password Password12!
```

to match the Travis configuration.

That said, I'm currently erroring on this with a `Couldn't create table` error so I'm not sure if there are other problems going on.

> Retriever's command line interface contains "new_json,edit_json,delete_json". Will mentioning creation of these functions in R in proposal be apt?

I'm not particularly concerned with these being in the R/Julia packages and I imagine that capturing the prompt from the CLI and the input from R and passing them back and forth would be tricky. So, I guess I'd lean towards not including them.

**Comment by ethanwhite** [comment]
@pranita-s I'm realizing that I'm actually not sure that we don't rely on `postgress.conn` in Python as well. That would be something to check. If we're using it in Python now then we may not need the extra code in R.

Take home - for the purposes of the proposal I think you can just state that R currently handles database configuration files itself, when it should be using the Python packages facilities for handling this to make it consistent.

**Comment by henrykironde** [comment]
We use connection info `https://github.com/ropensci/rdataretriever/blob/master/R/rdataretriever.R#L13` as stated here. The connection information is handled in the install function https://github.com/ropensci/rdataretriever/blob/master/R/rdataretriever.R#L30. 

In python we use the defaults in the respective engines or the values provided by the respective configuration files for the databases.  postgres `~/.pgpass`, mysql `my.cnf`
like Ethan said
`Take home - for the purposes of the proposal I think you can just state that R currently handles database configuration files itself, when it should be using the Python packages facilities for handling this to make it consistent. ` :+1:

**Comment by pranita-s** [comment]
@ethanwhite @henrykironde Thank you! Please let me know if I understood it wrong-
In cases where config information is not given through command line/arguments, Python takes info from `~/.pgpass` and `my.cnf`. R `install` function has to be altered to exhibit the same behaviour.

This triggered more doubts related to ideas list:

**Match the R install API to the Python install API while maintaining backward compatibility. Currently the R API uses a single install function instead of the suite of different install function in the Python interface.**
- Does it mean individual install functions for each database is required in R too?
- Also, so far `json` and `xml` support are missing from R API. There inclusion will be part of proposal?

**Expand the R API to include all features of the Python API**

- Excluded features are individual `install` functions, `create_home_dir()` and `set_proxy()`. Am I missing anything?

**Additions to ideas list for rdataretriever**


- Ideas list for python mentions adding spatial data support. R has package such as `sf` which provides support for spatial data such as trajectory data. Can spatial datasets be added for R API?
- Also,for Python there is an idea for creating a dashboard. R has RShiny utility for creation of UI/dashboard. Can it be included too?

**Comment by henrykironde** [comment]
`Thank you! Please let me know if I understood it wrong-
In cases where config information is not given through command line/arguments, Python takes info from ~/.pgpass and my.cnf. R install function has to be altered to exhibit the same behaviour.` 

When we use the python library, the CLI in this case, we can run something like

```batch
retriever install mysql --user myuser --password ******** --host localhost --port 8888 --database_name testdbase iris
```
In the example above, we are providing most of the arguments. However, we could do a quick run using 

```batch
retriever install mysql  iris
```
In the last example, I am not providing any arguments like user, password, etc. The retriever will look for that information in the default options' files `~/.pgpass and my.cnf.`  If the information in those files is setup right, it will use those values, else it will try to use the defaults supplied by each engine. 

Currently we call the retriever through R relying on `CLI` and we use the `.conn` files to provide the connection information like password and port. We could alter the behavior to avoid using `.conn` files since the `retriever CLI` that R utilizes uses `~/.pgpass and my.cnf.` if no arguments are passed.


`Does it mean individual install functions for each database is required in R too?`  Individual install functions could be another way.

`Also, so far json and xml support are missing from R API. There inclusion will be part of proposal?`
I do think they are [there](https://github.com/ropensci/rdataretriever/blob/master/R/rdataretriever.R#L69) 

```python
  else if (connection %in% c('csv', 'json', 'xml')) {
    cmd = paste('retriever install', connection, '--table_name',
                  file.path(data_dir, '{db}_{table}.csv'), dataset)
  }

`Excluded features are individual install functions, create_home_dir() and set_proxy(). Am I missing anything?` 
I think this comes back to the core function the python interface exhibits like installing into individual engines
https://github.com/weecology/retriever/blob/master/retriever/lib/install.py

`Ideas list for python mentions adding spatial data support. R has package such as sf which provides support for spatial data such as trajectory data. Can spatial datasets be added for R API?` Let us leave this out for now.

`Also, for Python, there is an idea for creating a dashboard. R has RShiny utility for creation of UI/dashboard. Can it be included too?`
 Sure it will be great to have some sort of visualization for the dataset. I do not recommend doing exactly like the Python dashboard. The idea behind that is a little more intricate. However, I excited to see your idea using RShiny. The Team will decide if that would be a good way to go but I am on board.

**Comment by ethanwhite** [comment]
:+1: to @henrykironde's points. Just to restate a couple of them for clarity. 

> Does it mean individual install functions for each database is required in R too?

We can leave the existing `install` function for backwards compatibility. Old code will still work the same way because we'll leave the general install function, but we'll also have `install_mysql`, `install_sqlite`, etc. to match the Python API. We may want to use `install()` inside the individual `install_*` functions anyway to avoid duplicate code. We do this with a hidden `_install()` function in the Python package:
https://github.com/weecology/retriever/blob/master/retriever/lib/install.py

> Excluded features are individual install functions, create_home_dir() and set_proxy()

These should actually be internal functions for Python, so I think the right solution is to make these private functions so they aren't in the Python API.
